//metodos de interaccion para los usuarios
###
GET http://localhost:9000/user/listAll


###
GET http://localhost:9000/user/query/2


###
POST http://localhost:9000/user/create
Content-Type: application/json

{
    "username": "juan camilo",
    "password": "Tragedia1234",
    "email": "pepegalindo@gmail.com"
}

###
PATCH http://localhost:9000/user/update/3
Content-Type: application/json

{
   "username": "juan carlos",
    "password": "Tragedia1234",
    "email": "pepegalindo@gmail.com"
}

###
DELETE http://localhost:9000/user/delete/1




//Metodos de interaccion para los libros
###
GET http://localhost:9000/Libros/listAll

###
GET http://localhost:9000/Libros//query/2

###
POST http://localhost:9000/Libros/create
Content-Type: application/json

{
    "titulo": "Glimpse of Us",
    "tipo": "Tragedia",
    "editorial": "Porrúa",
    "year": "2021",
    "autor": "Sófocles"
}

###
PATCH http://localhost:9000/Libros/update/2
Content-Type: application/json

{
   "titulo": "vale",
    "tipo": "Pop",
    "disquera": "Warner",
    "year": "2022",
    "autor": "Joji"
}

###
DELETE http://localhost:9000/Libros/delete/1



//Metodos de interaccion para la musica
###
GET http://localhost:9000/Musica/listAll

###
GET http://localhost:9000/Musica//query/1

###
POST http://localhost:9000/Musica/create
Content-Type: application/json

{
    "titulo": "Glimpse of Us",
    "tipo": "Pop",
    "disquera": "Warner",
    "year": "2021",
    "autor": "Joji"
}

###
PATCH http://localhost:9000/Musica/update/1
Content-Type: application/json

{
   "titulo": "Glimpse of Us",
    "tipo": "Pop",
    "disquera": "Warner",
    "year": "2022",
    "autor": "Joji"
}

###
DELETE http://localhost:9000/Musica/delete/1